from .animal import Animal
from .leech import Leech
from .lizard import Lizard
from .salamandar import Salamander
from .snake import Snake
from .worm import Worm
from .catfish import Catfish
from .dolphin import Dolphin
from .goldfish import Goldfish
from .shark import Shark
from .whale import Whale
from .cat import Cat
from .dog import Dog
from .goat import Goat
from .horse import Horse
from .camel import Camel